identidock:
  build: .
  ports:
    - "5000:5000"
  environment:
    ENV: DEV
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0

storage:
  filesystem:
    rootdirectofy: /var/lib/registry

http:
  addr: joo:5000
  secret: 9Ci5B8SN0yB5wa11t0oEHuUbn5wTLYWd
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key